from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from core.models import (
    AcquisitionWorklist,
    Experiment,
    Facility,
    Lab,
    LabMembership,
    ProcessingPipeline,
    Project,
    Run,
    RunFileRole,
    RunStatus,
    Sample,
    University,
    UserProfile,
    UserRole,
    WorklistEntry,
    WorklistStatus,
)


class Command(BaseCommand):
    help = "Create DIA-NN and Skyline real-engine worklists for files placed in incoming storage."

    def add_arguments(self, parser):
        parser.add_argument("--code", default="OPS-ENGINES")
        parser.add_argument("--diann-file", action="append", default=[])
        parser.add_argument("--skyline-file", action="append", default=[])
        parser.add_argument("--diann-executable", default="diann")
        parser.add_argument("--diann-version", default="site-pinned")
        parser.add_argument("--diann-fasta", default="")
        parser.add_argument("--diann-library", default="")
        parser.add_argument("--skyline-executable", default="SkylineCmd")
        parser.add_argument("--skyline-version", default="site-pinned")
        parser.add_argument("--skyline-document", default="")
        parser.add_argument("--skyline-report-name", default="Transition Results")
        parser.add_argument("--create-placeholders", action="store_true")

    def handle(self, *args, **options):
        if not options["diann_file"] and not options["skyline_file"]:
            raise CommandError("Provide at least one --diann-file or --skyline-file.")
        if options["skyline_file"] and not options["skyline_document"]:
            raise CommandError("--skyline-document is required when --skyline-file is provided.")

        incoming_root = Path(settings.INCOMING_RAW_ROOT)
        incoming_root.mkdir(parents=True, exist_ok=True)
        if options["create_placeholders"]:
            for filename in [*options["diann_file"], *options["skyline_file"]]:
                path = incoming_root / Path(filename).name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(f"MSConnect real-engine placeholder for {filename}\n", encoding="utf-8")

        with transaction.atomic():
            user = self._user()
            lab = self._lab(user)
            project, _created = Project.objects.update_or_create(
                lab=lab,
                code=options["code"],
                defaults={
                    "title": "Real engine operations project",
                    "pi": user,
                    "description": "Generated by create_engine_operations_fixture.",
                },
            )
            if options["diann_file"]:
                pipeline = self._diann_pipeline(options)
                self._worklist(
                    project=project,
                    user=user,
                    engine="diann",
                    filenames=options["diann_file"],
                    pipeline=pipeline,
                )
            if options["skyline_file"]:
                pipeline = self._skyline_pipeline(options)
                self._worklist(
                    project=project,
                    user=user,
                    engine="skyline",
                    filenames=options["skyline_file"],
                    pipeline=pipeline,
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"created engine operations fixture code={options['code']} "
                f"diann_files={len(options['diann_file'])} skyline_files={len(options['skyline_file'])}"
            )
        )

    def _worklist(self, *, project, user, engine, filenames, pipeline):
        experiment, _created = Experiment.objects.update_or_create(
            project=project,
            name=f"{engine.upper()} Operations Experiment",
            defaults={"created_by": user, "metadata": {"setup_source": "engine_operations_fixture", "engine": engine}},
        )
        worklist, _created = AcquisitionWorklist.objects.update_or_create(
            experiment=experiment,
            name=f"{engine.upper()} Operations Worklist",
            defaults={
                "status": WorklistStatus.READY,
                "generated_by": user,
                "metadata": {
                    "setup_source": "engine_operations_fixture",
                    "processing_pipeline_id": pipeline.id,
                    "required_engine": engine,
                    "watcher_matching": "expected_filename",
                },
            },
        )
        worklist.entries.all().delete()
        worklist.status = WorklistStatus.READY
        worklist.generated_by = user
        worklist.metadata = {
            **(worklist.metadata or {}),
            "setup_source": "engine_operations_fixture",
            "processing_pipeline_id": pipeline.id,
            "required_engine": engine,
            "watcher_matching": "expected_filename",
        }
        worklist.save(update_fields=["status", "generated_by", "metadata", "updated_at"])

        for position, filename in enumerate(filenames, start=1):
            sample, _created = Sample.objects.update_or_create(
                experiment=experiment,
                name=f"{engine.upper()} Sample {position:02d}",
                defaults={
                    "external_id": f"{project.code}-{engine}-{position:02d}",
                    "submitted_by": user,
                    "metadata": {"engine": engine},
                },
            )
            expected_filename = Path(filename).name
            run, _created = Run.objects.update_or_create(
                sample=sample,
                run_name=f"{project.code}-{engine}-{position:02d}",
                defaults={
                    "status": RunStatus.PLANNED,
                    "file_role": RunFileRole.SAMPLE,
                    "expected_filename": expected_filename,
                    "worklist_position": position,
                    "metadata": {"engine": engine, "expected_filename": expected_filename},
                },
            )
            WorklistEntry.objects.create(
                worklist=worklist,
                run=run,
                position=position,
                file_role=RunFileRole.SAMPLE,
                expected_filename=expected_filename,
                metadata={
                    "engine": engine,
                    "watcher_match_key": expected_filename,
                    "required_engine": engine,
                },
            )

    def _diann_pipeline(self, options):
        parameters = {
            "adapter": "diann",
            "required_engine": "diann",
            "executable": options["diann_executable"],
            "software_version": options["diann_version"],
            "version_command": [options["diann_executable"], "--version"],
            "report": "diann-report.tsv",
        }
        if options["diann_fasta"]:
            parameters["fasta"] = options["diann_fasta"]
        if options["diann_library"]:
            parameters["library"] = options["diann_library"]
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Real DIA-NN",
            version=options["diann_version"],
            defaults={"container_image": "site-managed-diann", "parameters": parameters},
        )
        return pipeline

    def _skyline_pipeline(self, options):
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Real Skyline",
            version=options["skyline_version"],
            defaults={
                "container_image": "site-managed-skyline",
                "parameters": {
                    "adapter": "skyline",
                    "required_engine": "skyline",
                    "executable": options["skyline_executable"],
                    "software_version": options["skyline_version"],
                    "version_command": [options["skyline_executable"], "--version"],
                    "document": options["skyline_document"],
                    "report": "skyline-report.csv",
                    "report_name": options["skyline_report_name"],
                },
            },
        )
        return pipeline

    def _user(self):
        User = get_user_model()
        user, created = User.objects.get_or_create(
            username="engine-ops-admin",
            defaults={"is_staff": True, "is_superuser": True, "email": "engine-ops@example.test"},
        )
        if created:
            user.set_unusable_password()
            user.save(update_fields=["password"])
        UserProfile.objects.update_or_create(user=user, defaults={"global_role": UserRole.ADMIN})
        return user

    def _lab(self, user):
        university, _created = University.objects.get_or_create(name="MSConnect Engine Operations University")
        facility, _created = Facility.objects.get_or_create(
            university=university,
            slug="engine-operations",
            defaults={"name": "Engine Operations Facility"},
        )
        lab, _created = Lab.objects.get_or_create(
            facility=facility,
            slug="engine-operations-lab",
            defaults={"name": "Engine Operations Lab", "pi": user},
        )
        if lab.pi_id != user.id:
            lab.pi = user
            lab.save(update_fields=["pi", "updated_at"])
        LabMembership.objects.update_or_create(user=user, lab=lab, defaults={"role": UserRole.ADMIN, "active": True})
        return lab
