import shutil
import sys
from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.utils import timezone

from core.models import (
    AcquisitionWorklist,
    Experiment,
    Facility,
    Lab,
    LabMembership,
    ProcessingPipeline,
    Project,
    Run,
    RunFileRole,
    Sample,
    University,
    UserProfile,
    UserRole,
    WorklistEntry,
    WorklistStatus,
)


class Command(BaseCommand):
    help = "Create a minimal end-to-end smoke fixture for watcher-to-processor validation."

    def add_arguments(self, parser):
        parser.add_argument("--code", default="")
        parser.add_argument("--raw-filename", default="")
        parser.add_argument(
            "--source-file",
            help="Optional real raw file to stage into INCOMING_RAW_ROOT instead of writing a placeholder.",
        )
        parser.add_argument(
            "--stage-method",
            choices=("copy", "symlink"),
            default="copy",
            help="How to stage --source-file into INCOMING_RAW_ROOT.",
        )

    def handle(self, *args, **options):
        code = options["code"] or f"E2E-SMOKE-{timezone.now().strftime('%Y%m%d%H%M%S')}"
        source_file = options["source_file"]
        if source_file:
            source_path = Path(source_file).expanduser()
            if not source_path.exists():
                raise CommandError(f"source file does not exist: {source_path}")
            raw_filename = options["raw_filename"] or source_path.name
        else:
            source_path = None
            raw_filename = options["raw_filename"] or f"{code}_run01.mzML"
        incoming_root = Path(settings.INCOMING_RAW_ROOT)
        incoming_root.mkdir(parents=True, exist_ok=True)
        raw_path = incoming_root / raw_filename
        if source_path:
            self._stage_source_file(source_path=source_path, destination=raw_path, stage_method=options["stage_method"])
        else:
            raw_path.write_text("MSConnect end-to-end smoke raw placeholder\n", encoding="utf-8")

        user = self._user()
        lab = self._lab(user)
        project, _created = Project.objects.update_or_create(
            code=code,
            defaults={
                "lab": lab,
                "title": "End-to-end smoke project",
                "pi": user,
                "description": "Generated by create_e2e_smoke_fixture.",
            },
        )
        experiment, _created = Experiment.objects.update_or_create(
            project=project,
            name="Smoke Experiment",
            defaults={"created_by": user, "metadata": {"setup_source": "e2e_smoke"}},
        )
        sample, _created = Sample.objects.update_or_create(
            experiment=experiment,
            name="Smoke Sample 1",
            defaults={"metadata": {"condition": "smoke"}},
        )
        run, _created = Run.objects.update_or_create(
            sample=sample,
            run_name=f"{code} run01",
            defaults={
                "expected_filename": raw_filename,
                "file_role": RunFileRole.SAMPLE,
                "metadata": {"watcher_match_key": raw_filename},
            },
        )
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="E2E Smoke Processor",
            version="1.0",
            defaults={
                "container_image": settings.MSCONNECT_IMAGE,
                "parameters": {
                    "command": [
                        sys.executable,
                        "manage.py",
                        "seed_demo_showcase",
                        "--write-job-results",
                        "{job_id}",
                        "{results_dir}",
                    ],
                    "working_dir": str(settings.BASE_DIR),
                    "result_files": {
                        "protein_table": "proteins.csv",
                        "peptide_table": "peptides.csv",
                        "delimiter": ",",
                    },
                    "stats_json": "stats.json",
                },
            },
        )
        worklist, _created = AcquisitionWorklist.objects.update_or_create(
            experiment=experiment,
            name="E2E Smoke Worklist",
            defaults={
                "status": WorklistStatus.READY,
                "generated_by": user,
                "metadata": {
                    "setup_source": "e2e_smoke",
                    "processing_pipeline_id": pipeline.id,
                    "watcher_matching": "expected_filename",
                },
            },
        )
        WorklistEntry.objects.update_or_create(
            worklist=worklist,
            position=1,
            defaults={
                "run": run,
                "expected_filename": raw_filename,
                "file_role": RunFileRole.SAMPLE,
                "metadata": {"watcher_match_key": raw_filename},
            },
        )

        self.stdout.write(
            self.style.SUCCESS(
                f"created e2e smoke fixture code={code} raw_file={raw_path} pipeline={pipeline.id}"
            )
        )

    def _stage_source_file(self, *, source_path: Path, destination: Path, stage_method: str):
        destination.parent.mkdir(parents=True, exist_ok=True)
        if destination.exists():
            destination.unlink()
        if stage_method == "symlink":
            destination.symlink_to(source_path.resolve())
            return
        shutil.copy2(source_path, destination)

    def _user(self):
        User = get_user_model()
        user, created = User.objects.get_or_create(username="e2e-smoke-admin", defaults={"is_staff": True})
        if created:
            user.set_unusable_password()
            user.save(update_fields=["password"])
        UserProfile.objects.get_or_create(user=user, defaults={"global_role": UserRole.ADMIN})
        return user

    def _lab(self, user):
        university, _created = University.objects.get_or_create(name="MSConnect Smoke University")
        facility, _created = Facility.objects.get_or_create(
            university=university,
            slug="msconnect-smoke",
            defaults={"name": "MSConnect Smoke Facility"},
        )
        lab, _created = Lab.objects.get_or_create(
            facility=facility,
            slug="msconnect-smoke-lab",
            defaults={"name": "MSConnect Smoke Lab", "pi": user},
        )
        LabMembership.objects.get_or_create(user=user, lab=lab, defaults={"role": UserRole.ADMIN})
        return lab
