from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from core.models import (
    AcquisitionWorklist,
    Experiment,
    Facility,
    Lab,
    LabMembership,
    ProcessingPipeline,
    Project,
    QcProgram,
    Run,
    RunFileRole,
    RunStatus,
    Sample,
    University,
    UserProfile,
    UserRole,
    WorklistEntry,
    WorklistStatus,
)


class Command(BaseCommand):
    help = "Create a filename-driven acquisition worklist that matches expected raw filenames exactly."

    def add_arguments(self, parser):
        parser.add_argument("--code", required=True, help="Project code to create or reuse.")
        parser.add_argument(
            "--project-title",
            default="Filename matching project",
            help="Project title to store on the created project.",
        )
        parser.add_argument(
            "--worklist-name",
            default="Filename matching worklist",
            help="Worklist name to store on the created acquisition worklist.",
        )
        parser.add_argument(
            "--filenames-file",
            help="Optional text file with one filename per line. Blank lines and lines starting with # are ignored.",
        )
        parser.add_argument(
            "--filename",
            action="append",
            default=[],
            help="Explicit filename to add to the worklist. May be repeated.",
        )
        parser.add_argument(
            "--pipeline-name",
            default="Filename matching DIA-NN",
            help="Processing pipeline name to attach to the worklist metadata.",
        )
        parser.add_argument(
            "--pipeline-version",
            default="site-managed",
            help="Processing pipeline version to attach to the worklist metadata.",
        )
        parser.add_argument(
            "--notes",
            default="Generated from raw file names for watcher matching and upload smoke testing.",
            help="Free-form notes for the worklist.",
        )
        parser.add_argument(
            "--create-placeholders",
            action="store_true",
            help="Write placeholder files with the same basenames into INCOMING_RAW_ROOT.",
        )

    def handle(self, *args, **options):
        filenames = self._load_filenames(options["filenames_file"], options["filename"])
        if not filenames:
            raise CommandError("Provide at least one filename via --filename or --filenames-file.")

        incoming_root = Path(settings.INCOMING_RAW_ROOT)
        incoming_root.mkdir(parents=True, exist_ok=True)

        with transaction.atomic():
            user = self._ensure_user()
            lab = self._ensure_lab(user)
            project, _created = Project.objects.update_or_create(
                lab=lab,
                code=str(options["code"]).strip(),
                defaults={
                    "title": str(options["project_title"]).strip(),
                    "pi": user,
                    "description": "Generated by create_filename_worklist.",
                },
            )
            experiment, _created = Experiment.objects.update_or_create(
                project=project,
                name="Filename Matching Experiment",
                defaults={"created_by": user, "metadata": {"setup_source": "filename_worklist"}},
            )
            pipeline = self._pipeline(
                name=str(options["pipeline_name"]).strip(),
                version=str(options["pipeline_version"]).strip(),
            )
            worklist, _created = AcquisitionWorklist.objects.update_or_create(
                experiment=experiment,
                name=str(options["worklist_name"]).strip(),
                defaults={
                    "status": WorklistStatus.READY,
                    "generated_by": user,
                    "notes": str(options["notes"]).strip(),
                    "metadata": {
                        "setup_source": "filename_worklist",
                        "processing_pipeline_id": pipeline.id,
                        "required_engine": "diann",
                        "watcher_matching": "expected_filename",
                    },
                },
            )
            worklist.entries.all().delete()
            worklist.status = WorklistStatus.READY
            worklist.generated_by = user
            worklist.notes = str(options["notes"]).strip()
            worklist.metadata = {
                **(worklist.metadata or {}),
                "setup_source": "filename_worklist",
                "processing_pipeline_id": pipeline.id,
                "required_engine": "diann",
                "watcher_matching": "expected_filename",
                "filename_count": len(filenames),
            }
            worklist.save(update_fields=["status", "generated_by", "notes", "metadata", "updated_at"])

            for position, filename in enumerate(filenames, start=1):
                self._entry(
                    project=project,
                    experiment=experiment,
                    worklist=worklist,
                    position=position,
                    filename=filename,
                    user=user,
                )
                if options["create_placeholders"]:
                    placeholder = incoming_root / Path(filename).name
                    placeholder.parent.mkdir(parents=True, exist_ok=True)
                    placeholder.write_text(
                        f"MSConnect filename worklist placeholder\nproject={project.code}\nfilename={Path(filename).name}\n",
                        encoding="utf-8",
                    )

        self.stdout.write(
            self.style.SUCCESS(
                f"created filename worklist code={project.code} worklist={worklist.name} files={len(filenames)}"
            )
        )

    def _load_filenames(self, filenames_file, filenames):
        loaded = []
        if filenames_file:
            path = Path(filenames_file)
            if not path.exists():
                raise CommandError(f"filenames file does not exist: {path}")
            for line in path.read_text(encoding="utf-8").splitlines():
                value = line.strip()
                if value and not value.startswith("#"):
                    loaded.append(value)
        loaded.extend([value.strip() for value in filenames if value and value.strip()])
        seen = set()
        unique = []
        for value in loaded:
            basename = Path(value).name
            if basename not in seen:
                seen.add(basename)
                unique.append(value)
        return unique

    def _ensure_user(self):
        User = get_user_model()
        user, _created = User.objects.get_or_create(
            username="worklist-bot",
            defaults={"email": "worklist-bot@example.test"},
        )
        if not user.is_staff:
            user.is_staff = True
        if not user.is_superuser:
            user.is_superuser = True
        if not user.email:
            user.email = "worklist-bot@example.test"
        user.save(update_fields=["email", "is_staff", "is_superuser"])
        UserProfile.objects.update_or_create(user=user, defaults={"global_role": UserRole.ADMIN})
        return user

    def _ensure_lab(self, user):
        university, _created = University.objects.get_or_create(name="MSConnect Lab")
        facility, _created = Facility.objects.get_or_create(
            university=university,
            slug="filename-matching-core",
            defaults={"name": "Filename Matching Core"},
        )
        lab, _created = Lab.objects.get_or_create(
            facility=facility,
            slug="filename-matching",
            defaults={"name": "Filename Matching Lab", "pi": user},
        )
        if lab.pi_id != user.id:
            lab.pi = user
            lab.save(update_fields=["pi"])
        LabMembership.objects.update_or_create(user=user, lab=lab, defaults={"role": UserRole.ADMIN, "active": True})
        return lab

    def _pipeline(self, *, name, version):
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name=name,
            version=version,
            defaults={
                "container_image": "site-managed-diann",
                "parameters": {
                    "adapter": "diann",
                    "required_engine": "diann",
                    "required_engine_version": "",
                },
            },
        )
        return pipeline

    def _entry(self, *, project, experiment, worklist, position, filename, user):
        basename = Path(filename).name
        stem = Path(basename).stem
        file_role, qc_program = self._infer_role(stem)
        sample, _created = Sample.objects.update_or_create(
            experiment=experiment,
            name=stem,
            defaults={
                "external_id": f"{project.code}-{position:03d}",
                "submitted_by": user,
                "metadata": {
                    "setup_source": "filename_worklist",
                    "filename": basename,
                    "file_role": file_role,
                    "qc_program": qc_program,
                },
            },
        )
        run_name = f"{project.code}-{position:03d}-{stem}"
        run, _created = Run.objects.update_or_create(
            sample=sample,
            run_name=run_name,
            defaults={
                "status": RunStatus.PLANNED,
                "file_role": file_role,
                "qc_program": qc_program,
                "expected_filename": basename,
                "worklist_position": position,
                "metadata": {
                    "setup_source": "filename_worklist",
                    "expected_filename": basename,
                    "original_filename": filename,
                },
            },
        )
        WorklistEntry.objects.create(
            worklist=worklist,
            run=run,
            position=position,
            file_role=file_role,
            qc_program=qc_program,
            expected_filename=basename,
            block_label=project.code,
            metadata={
                "setup_source": "filename_worklist",
                "watcher_match_key": basename,
                "original_filename": filename,
                "file_role": file_role,
                "qc_program": qc_program,
            },
        )

    def _infer_role(self, stem):
        lower = stem.lower()
        if "prtc" in lower:
            return RunFileRole.PRTC, QcProgram.PRTC
        if "hye" in lower:
            return RunFileRole.HYE, QcProgram.HYE
        if "wash" in lower:
            return RunFileRole.WASH, QcProgram.NONE
        if "postblank" in lower or "true_blank" in lower or lower.endswith("_blank") or "blank" in lower:
            return RunFileRole.TRUE_BLANK, QcProgram.NONE
        return RunFileRole.SAMPLE, QcProgram.NONE
