from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction

from core.models import (
    AcquisitionWorklist,
    Experiment,
    Facility,
    Lab,
    LabMembership,
    ProcessingPipeline,
    Project,
    Run,
    RunFileRole,
    RunStatus,
    Sample,
    University,
    UserProfile,
    UserRole,
    WorklistEntry,
    WorklistStatus,
)
from core.processing.registry import resolve_pipeline_parameters


class Command(BaseCommand):
    help = "Create DIA-NN, FragPipe, and Skyline real-engine worklists for files placed in incoming storage."

    def add_arguments(self, parser):
        parser.add_argument("--code", default="OPS-ENGINES")
        parser.add_argument("--diann-file", action="append", default=[])
        parser.add_argument("--skyline-file", action="append", default=[])
        parser.add_argument("--diann-executable", default="diann")
        parser.add_argument("--diann-version", default="site-pinned")
        parser.add_argument("--diann-fasta", default="")
        parser.add_argument("--diann-fasta-ref", default="")
        parser.add_argument("--diann-library", default="")
        parser.add_argument("--diann-library-ref", default="")
        parser.add_argument("--diann-settings-key", default="")
        parser.add_argument("--fragpipe-file", action="append", default=[])
        parser.add_argument("--fragpipe-executable", default="fragpipe")
        parser.add_argument("--fragpipe-version", default="site-pinned")
        parser.add_argument("--fragpipe-workflow", default="")
        parser.add_argument("--fragpipe-workflow-ref", default="")
        parser.add_argument("--fragpipe-fasta", default="")
        parser.add_argument("--fragpipe-fasta-ref", default="")
        parser.add_argument("--fragpipe-settings-key", default="")
        parser.add_argument("--fragpipe-threads", type=int)
        parser.add_argument("--fragpipe-ram-gb", type=int)
        parser.add_argument("--skyline-executable", default="SkylineCmd")
        parser.add_argument("--skyline-version", default="site-pinned")
        parser.add_argument("--skyline-document", default="")
        parser.add_argument("--skyline-document-ref", default="")
        parser.add_argument("--skyline-settings-key", default="")
        parser.add_argument("--skyline-report-name", default="Transition Results")
        parser.add_argument("--create-placeholders", action="store_true")

    def handle(self, *args, **options):
        if not options["diann_file"] and not options["fragpipe_file"] and not options["skyline_file"]:
            raise CommandError("Provide at least one --diann-file, --fragpipe-file, or --skyline-file.")
        if options["fragpipe_file"] and not (options["fragpipe_workflow"] or options["fragpipe_workflow_ref"]):
            raise CommandError(
                "--fragpipe-workflow or --fragpipe-workflow-ref is required when --fragpipe-file is provided."
            )
        if options["skyline_file"] and not (options["skyline_document"] or options["skyline_document_ref"]):
            raise CommandError(
                "--skyline-document or --skyline-document-ref is required when --skyline-file is provided."
            )

        incoming_root = Path(settings.INCOMING_RAW_ROOT)
        incoming_root.mkdir(parents=True, exist_ok=True)
        if options["create_placeholders"]:
            for filename in [*options["diann_file"], *options["fragpipe_file"], *options["skyline_file"]]:
                path = incoming_root / Path(filename).name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(f"MSConnect real-engine placeholder for {filename}\n", encoding="utf-8")

        with transaction.atomic():
            user = self._user()
            lab = self._lab(user)
            project, _created = Project.objects.update_or_create(
                lab=lab,
                code=options["code"],
                defaults={
                    "title": "Real engine operations project",
                    "pi": user,
                    "description": "Generated by create_engine_operations_fixture.",
                },
            )
            if options["diann_file"]:
                pipeline = self._diann_pipeline(options)
                self._worklist(
                    project=project,
                    user=user,
                    engine="diann",
                    filenames=options["diann_file"],
                    pipeline=pipeline,
                )
            if options["fragpipe_file"]:
                pipeline = self._fragpipe_pipeline(options)
                self._worklist(
                    project=project,
                    user=user,
                    engine="fragpipe",
                    filenames=options["fragpipe_file"],
                    pipeline=pipeline,
                )
            if options["skyline_file"]:
                pipeline = self._skyline_pipeline(options)
                self._worklist(
                    project=project,
                    user=user,
                    engine="skyline",
                    filenames=options["skyline_file"],
                    pipeline=pipeline,
                )

        self.stdout.write(
            self.style.SUCCESS(
                f"created engine operations fixture code={options['code']} "
                f"diann_files={len(options['diann_file'])} "
                f"fragpipe_files={len(options['fragpipe_file'])} "
                f"skyline_files={len(options['skyline_file'])}"
            )
        )

    def _worklist(self, *, project, user, engine, filenames, pipeline):
        experiment, _created = Experiment.objects.update_or_create(
            project=project,
            name=f"{engine.upper()} Operations Experiment",
            defaults={"created_by": user, "metadata": {"setup_source": "engine_operations_fixture", "engine": engine}},
        )
        worklist, _created = AcquisitionWorklist.objects.update_or_create(
            experiment=experiment,
            name=f"{engine.upper()} Operations Worklist",
            defaults={
                "status": WorklistStatus.READY,
                "generated_by": user,
                "metadata": {
                    "setup_source": "engine_operations_fixture",
                    "processing_pipeline_id": pipeline.id,
                    "required_engine": engine,
                    "watcher_matching": "expected_filename",
                },
            },
        )
        worklist.entries.all().delete()
        worklist.status = WorklistStatus.READY
        worklist.generated_by = user
        worklist.metadata = {
            **(worklist.metadata or {}),
            "setup_source": "engine_operations_fixture",
            "processing_pipeline_id": pipeline.id,
            "required_engine": engine,
            "watcher_matching": "expected_filename",
        }
        worklist.save(update_fields=["status", "generated_by", "metadata", "updated_at"])

        for position, filename in enumerate(filenames, start=1):
            sample, _created = Sample.objects.update_or_create(
                experiment=experiment,
                name=f"{engine.upper()} Sample {position:02d}",
                defaults={
                    "external_id": f"{project.code}-{engine}-{position:02d}",
                    "submitted_by": user,
                    "metadata": {"engine": engine},
                },
            )
            expected_filename = Path(filename).name
            run, _created = Run.objects.update_or_create(
                sample=sample,
                run_name=f"{project.code}-{engine}-{position:02d}",
                defaults={
                    "status": RunStatus.PLANNED,
                    "file_role": RunFileRole.SAMPLE,
                    "expected_filename": expected_filename,
                    "worklist_position": position,
                    "metadata": {"engine": engine, "expected_filename": expected_filename},
                },
            )
            WorklistEntry.objects.create(
                worklist=worklist,
                run=run,
                position=position,
                file_role=RunFileRole.SAMPLE,
                expected_filename=expected_filename,
                metadata={
                    "engine": engine,
                    "watcher_match_key": expected_filename,
                    "required_engine": engine,
                },
            )

    def _diann_pipeline(self, options):
        parameters = {
            "adapter": "diann",
            "required_engine": "diann",
            "required_engine_version": options["diann_version"],
            "executable": options["diann_executable"],
            "software_version": options["diann_version"],
            "version_command": [options["diann_executable"]],
            "report": "diann-report.parquet",
        }
        if options["diann_settings_key"]:
            parameters["settings_ref"] = options["diann_settings_key"]
        if options["diann_fasta"]:
            parameters["fasta"] = options["diann_fasta"]
        if options["diann_fasta_ref"]:
            parameters["fasta_ref"] = options["diann_fasta_ref"]
        if options["diann_library"]:
            parameters["library"] = options["diann_library"]
        if options["diann_library_ref"]:
            parameters["library_ref"] = options["diann_library_ref"]
        parameters = resolve_pipeline_parameters(parameters, engine="diann")
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Real DIA-NN",
            version=options["diann_version"],
            defaults={"container_image": "site-managed-diann", "parameters": parameters},
        )
        return pipeline

    def _fragpipe_pipeline(self, options):
        parameters = {
            "adapter": "fragpipe",
            "required_engine": "fragpipe",
            "executable": options["fragpipe_executable"],
            "software_version": options["fragpipe_version"],
            "version_command": [options["fragpipe_executable"], "--version"],
        }
        if options["fragpipe_settings_key"]:
            parameters["settings_ref"] = options["fragpipe_settings_key"]
        if options["fragpipe_workflow"]:
            parameters["workflow"] = options["fragpipe_workflow"]
        if options["fragpipe_workflow_ref"]:
            parameters["workflow_ref"] = options["fragpipe_workflow_ref"]
        if options["fragpipe_fasta"]:
            parameters["fasta"] = options["fragpipe_fasta"]
        if options["fragpipe_fasta_ref"]:
            parameters["fasta_ref"] = options["fragpipe_fasta_ref"]
        if options["fragpipe_threads"]:
            parameters["threads"] = options["fragpipe_threads"]
        if options["fragpipe_ram_gb"]:
            parameters["ram_gb"] = options["fragpipe_ram_gb"]
        parameters = resolve_pipeline_parameters(parameters, engine="fragpipe")
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Real FragPipe",
            version=options["fragpipe_version"],
            defaults={"container_image": "site-managed-fragpipe", "parameters": parameters},
        )
        return pipeline

    def _skyline_pipeline(self, options):
        parameters = {
            "adapter": "skyline",
            "required_engine": "skyline",
            "executable": options["skyline_executable"],
            "software_version": options["skyline_version"],
            "version_command": [options["skyline_executable"], "--version"],
            "report": "skyline-report.csv",
            "report_name": options["skyline_report_name"],
        }
        if options["skyline_settings_key"]:
            parameters["settings_ref"] = options["skyline_settings_key"]
        if options["skyline_document"]:
            parameters["document"] = options["skyline_document"]
        if options["skyline_document_ref"]:
            parameters["document_ref"] = options["skyline_document_ref"]
        parameters = resolve_pipeline_parameters(parameters, engine="skyline")
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Skyline Targeted",
            version=options["skyline_version"],
            defaults={
                "container_image": "site-managed-skyline",
                "parameters": parameters,
            },
        )
        return pipeline

    def _user(self):
        User = get_user_model()
        user, created = User.objects.get_or_create(
            username="engine-ops-admin",
            defaults={"is_staff": True, "is_superuser": True, "email": "engine-ops@example.test"},
        )
        if created:
            user.set_unusable_password()
            user.save(update_fields=["password"])
        UserProfile.objects.update_or_create(user=user, defaults={"global_role": UserRole.ADMIN})
        return user

    def _lab(self, user):
        university, _created = University.objects.get_or_create(name="MSConnect Engine Operations University")
        facility, _created = Facility.objects.get_or_create(
            university=university,
            slug="engine-operations",
            defaults={"name": "Engine Operations Facility"},
        )
        lab, _created = Lab.objects.get_or_create(
            facility=facility,
            slug="engine-operations-lab",
            defaults={"name": "Engine Operations Lab", "pi": user},
        )
        if lab.pi_id != user.id:
            lab.pi = user
            lab.save(update_fields=["pi", "updated_at"])
        LabMembership.objects.update_or_create(user=user, lab=lab, defaults={"role": UserRole.ADMIN, "active": True})
        return lab
