import sys
from pathlib import Path

from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand
from django.db import transaction

from core.models import (
    AcquisitionWorklist,
    Experiment,
    Facility,
    Lab,
    LabMembership,
    ProcessingPipeline,
    Project,
    QcProgram,
    Run,
    RunFileRole,
    RunStatus,
    Sample,
    University,
    UserProfile,
    UserRole,
    WorklistEntry,
    WorklistStatus,
)


class Command(BaseCommand):
    help = "Create a multi-project tagged operations fixture for watcher/processor validation."

    def add_arguments(self, parser):
        parser.add_argument("--code-prefix", default="OPS-TAGGED")
        parser.add_argument("--project-count", type=int, default=2)
        parser.add_argument("--sample-count", type=int, default=2)
        parser.add_argument("--raw-extension", default=".mzML")

    def handle(self, *args, **options):
        project_count = max(1, int(options["project_count"]))
        sample_count = max(1, int(options["sample_count"]))
        raw_extension = self._raw_extension(options["raw_extension"])
        code_prefix = str(options["code_prefix"]).strip() or "OPS-TAGGED"

        incoming_root = Path(settings.INCOMING_RAW_ROOT)
        incoming_root.mkdir(parents=True, exist_ok=True)

        with transaction.atomic():
            user = self._user()
            lab = self._lab(user)
            pipeline = self._pipeline()
            projects = []
            for project_index in range(1, project_count + 1):
                projects.append(
                    self._project_fixture(
                        code=f"{code_prefix}-{project_index:02d}",
                        project_index=project_index,
                        sample_count=sample_count,
                        raw_extension=raw_extension,
                        incoming_root=incoming_root,
                        user=user,
                        lab=lab,
                        pipeline=pipeline,
                    )
                )

        total_entries = sum(project["entry_count"] for project in projects)
        self.stdout.write(
            self.style.SUCCESS(
                f"created tagged operations fixture prefix={code_prefix} "
                f"projects={len(projects)} entries={total_entries} incoming={incoming_root}"
            )
        )

    def _project_fixture(
        self,
        *,
        code,
        project_index,
        sample_count,
        raw_extension,
        incoming_root,
        user,
        lab,
        pipeline,
    ):
        project, _created = Project.objects.update_or_create(
            lab=lab,
            code=code,
            defaults={
                "title": f"Tagged operations smoke project {project_index}",
                "pi": user,
                "description": "Generated by create_tagged_operations_fixture.",
            },
        )
        experiment, _created = Experiment.objects.update_or_create(
            project=project,
            name="Tagged Operations Experiment",
            defaults={"created_by": user, "metadata": {"setup_source": "tagged_operations_fixture"}},
        )
        worklist, _created = AcquisitionWorklist.objects.update_or_create(
            experiment=experiment,
            name="Tagged Operations Worklist",
            defaults={
                "status": WorklistStatus.READY,
                "generated_by": user,
                "notes": "Generated for watcher, processor, HYE, and PRTC tagged-run smoke testing.",
                "metadata": {
                    "setup_source": "tagged_operations_fixture",
                    "processing_pipeline_id": pipeline.id,
                    "watcher_matching": "expected_filename",
                },
            },
        )
        worklist.status = WorklistStatus.READY
        worklist.generated_by = user
        worklist.metadata = {
            **(worklist.metadata or {}),
            "setup_source": "tagged_operations_fixture",
            "processing_pipeline_id": pipeline.id,
            "watcher_matching": "expected_filename",
        }
        worklist.save(update_fields=["status", "generated_by", "metadata", "updated_at"])
        worklist.entries.all().delete()

        definitions = [
            *[
                {
                    "sample_name": f"Sample-{index:02d}",
                    "role": RunFileRole.SAMPLE,
                    "qc_program": QcProgram.NONE,
                    "hye_pair_label": "",
                }
                for index in range(1, sample_count + 1)
            ],
            {
                "sample_name": "HYE-A",
                "role": RunFileRole.HYE,
                "qc_program": QcProgram.HYE,
                "hye_pair_label": "HYE-01",
            },
            {
                "sample_name": "HYE-B",
                "role": RunFileRole.HYE,
                "qc_program": QcProgram.HYE,
                "hye_pair_label": "HYE-01",
            },
            {
                "sample_name": "PRTC-Std",
                "role": RunFileRole.PRTC,
                "qc_program": QcProgram.PRTC,
                "hye_pair_label": "",
            },
            {
                "sample_name": "Library",
                "role": RunFileRole.LIBRARY,
                "qc_program": QcProgram.NONE,
                "hye_pair_label": "",
            },
            {
                "sample_name": "Blank",
                "role": RunFileRole.BLANK,
                "qc_program": QcProgram.NONE,
                "hye_pair_label": "",
            },
            {
                "sample_name": "Wash",
                "role": RunFileRole.WASH,
                "qc_program": QcProgram.NONE,
                "hye_pair_label": "",
            },
        ]

        for position, definition in enumerate(definitions, start=1):
            self._entry(
                project=project,
                experiment=experiment,
                worklist=worklist,
                position=position,
                raw_extension=raw_extension,
                incoming_root=incoming_root,
                user=user,
                **definition,
            )

        return {"project": project, "entry_count": len(definitions)}

    def _entry(
        self,
        *,
        project,
        experiment,
        worklist,
        position,
        sample_name,
        role,
        qc_program,
        hye_pair_label,
        raw_extension,
        incoming_root,
        user,
    ):
        sample, _created = Sample.objects.update_or_create(
            experiment=experiment,
            name=sample_name,
            defaults={
                "external_id": f"{project.code}-{sample_name}",
                "submitted_by": user,
                "metadata": {
                    "setup_source": "tagged_operations_fixture",
                    "qc_program": qc_program,
                    "file_role": role,
                },
            },
        )
        expected_filename = f"{project.code}_{position:03d}_{sample_name.replace('-', '_')}{raw_extension}"
        run, _created = Run.objects.update_or_create(
            sample=sample,
            run_name=f"{project.code}-{position:03d}-{sample_name}",
            defaults={
                "status": RunStatus.PLANNED,
                "file_role": role,
                "qc_program": qc_program,
                "expected_filename": expected_filename,
                "worklist_position": position,
                "hye_pair_label": hye_pair_label,
                "metadata": {
                    "setup_source": "tagged_operations_fixture",
                    "expected_filename": expected_filename,
                    "qc_program": qc_program,
                    "synthetic_peptides_present": qc_program == QcProgram.PRTC,
                },
            },
        )
        WorklistEntry.objects.create(
            worklist=worklist,
            run=run,
            position=position,
            file_role=role,
            qc_program=qc_program,
            expected_filename=expected_filename,
            hye_pair_label=hye_pair_label,
            block_label=f"Project {project.code}",
            metadata={
                "setup_source": "tagged_operations_fixture",
                "watcher_match_key": expected_filename,
                "sample_name": sample.name,
                "sample_external_id": sample.external_id,
                "qc_program": qc_program,
                "synthetic_peptides_present": qc_program == QcProgram.PRTC,
            },
        )
        (incoming_root / expected_filename).write_text(
            f"MSConnect tagged operations fixture\nproject={project.code}\nposition={position}\nrole={role}\n",
            encoding="utf-8",
        )

    def _pipeline(self):
        pipeline, _created = ProcessingPipeline.objects.update_or_create(
            name="Tagged Operations Smoke Processor",
            version="1.0",
            defaults={
                "container_image": settings.MSCONNECT_IMAGE,
                "parameters": {
                    "command": [
                        sys.executable,
                        "manage.py",
                        "seed_demo_showcase",
                        "--write-job-results",
                        "{job_id}",
                        "{results_dir}",
                    ],
                    "working_dir": str(settings.BASE_DIR),
                    "result_files": {
                        "protein_table": "proteins.csv",
                        "peptide_table": "peptides.csv",
                        "delimiter": ",",
                    },
                },
            },
        )
        return pipeline

    def _user(self):
        User = get_user_model()
        user, created = User.objects.get_or_create(
            username="tagged-ops-admin",
            defaults={"is_staff": True, "is_superuser": True, "email": "tagged-ops@example.test"},
        )
        if created:
            user.set_unusable_password()
            user.save(update_fields=["password"])
        UserProfile.objects.update_or_create(user=user, defaults={"global_role": UserRole.ADMIN})
        return user

    def _lab(self, user):
        university, _created = University.objects.get_or_create(name="MSConnect Tagged Operations University")
        facility, _created = Facility.objects.get_or_create(
            university=university,
            slug="tagged-operations",
            defaults={"name": "Tagged Operations Facility"},
        )
        lab, _created = Lab.objects.get_or_create(
            facility=facility,
            slug="tagged-operations-lab",
            defaults={"name": "Tagged Operations Lab", "pi": user},
        )
        if lab.pi_id != user.id:
            lab.pi = user
            lab.save(update_fields=["pi", "updated_at"])
        LabMembership.objects.update_or_create(user=user, lab=lab, defaults={"role": UserRole.ADMIN, "active": True})
        return lab

    def _raw_extension(self, value):
        raw_extension = str(value or ".mzML").strip()
        if not raw_extension.startswith("."):
            raw_extension = f".{raw_extension}"
        return raw_extension
