# Generated by MSConnect.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_backfill_processing_artifacts_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="FindingsWorkspace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mode", models.CharField(default="personal", max_length=32)),
                ("data_strategy", models.CharField(default="manifest", max_length=32)),
                ("root_path", models.TextField()),
                ("workspace_path", models.TextField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("active", "Active"),
                            ("indexed", "Indexed"),
                            ("error", "Error"),
                        ],
                        default="prepared",
                        max_length=32,
                    ),
                ),
                ("plugin_marketplace", models.CharField(default="mriffle/findings-ai-collab-workflow", max_length=255)),
                ("plugin_name", models.CharField(default="findings-workflow", max_length=128)),
                ("plugin_version", models.CharField(blank=True, max_length=64)),
                ("findings_count", models.PositiveIntegerField(default=0)),
                ("reports_count", models.PositiveIntegerField(default=0)),
                ("latest_report_path", models.TextField(blank=True)),
                ("last_indexed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="findings_workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings_workspace",
                        to="core.project",
                    ),
                ),
            ],
            options={"ordering": ("project__code",)},
        ),
    ]
