# Generated by Django 5.2.15 on 2026-07-17 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_projectintakerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("node_type", models.CharField(default="diann", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("idle", "Idle"),
                            ("busy", "Busy"),
                            ("error", "Error"),
                        ],
                        default="offline",
                        max_length=32,
                    ),
                ),
                ("container_image", models.CharField(blank=True, max_length=255)),
                ("endpoint_url", models.URLField(blank=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="rawfile",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="rawfile",
            name="match_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="expected_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="run",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="hye_pair_label",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="run",
            name="worklist_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AcquisitionWorklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("acquiring", "Acquiring"),
                            ("complete", "Complete"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worklists",
                        to="core.instrumentconfiguration",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worklists",
                        to="core.experiment",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generated_worklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="WorklistEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "file_role",
                    models.CharField(
                        choices=[
                            ("sample", "Sample"),
                            ("qc", "QC"),
                            ("library", "Library"),
                            ("blank", "Blank"),
                            ("wash", "Wash"),
                            ("calibration", "Calibration"),
                        ],
                        default="sample",
                        max_length=32,
                    ),
                ),
                ("expected_filename", models.CharField(max_length=255)),
                ("injection_volume_ul", models.FloatField(blank=True, null=True)),
                ("hye_pair_label", models.CharField(blank=True, max_length=64)),
                ("block_label", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worklist_entry",
                        to="core.run",
                    ),
                ),
                (
                    "worklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.acquisitionworklist",
                    ),
                ),
            ],
            options={
                "ordering": ("worklist", "position"),
            },
        ),
        migrations.AddConstraint(
            model_name="acquisitionworklist",
            constraint=models.UniqueConstraint(
                fields=("experiment", "name"), name="uniq_worklist_name_per_experiment"
            ),
        ),
        migrations.AddConstraint(
            model_name="worklistentry",
            constraint=models.UniqueConstraint(
                fields=("worklist", "position"), name="uniq_worklist_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="worklistentry",
            constraint=models.UniqueConstraint(
                fields=("worklist", "expected_filename"),
                name="uniq_worklist_expected_filename",
            ),
        ),
    ]
