# Generated by Codex on 2026-07-17

import django.db.models.deletion
from django.db import migrations, models


def forwards_status(apps, _schema_editor):
    ProcessingJob = apps.get_model("core", "ProcessingJob")
    ProcessingJob.objects.filter(status="succeeded").update(status="complete")


def backwards_status(apps, _schema_editor):
    ProcessingJob = apps.get_model("core", "ProcessingJob")
    ProcessingJob.objects.filter(status="complete").update(status="succeeded")
    ProcessingJob.objects.filter(status__in=("assigned", "retrying")).update(status="queued")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_processingnode_rawfile_file_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processing_jobs",
                to="core.processingnode",
            ),
        ),
        migrations.RunPython(forwards_status, backwards_status),
        migrations.AlterField(
            model_name="processingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("assigned", "Assigned"),
                    ("running", "Running"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
