# Generated by Codex on 2026-07-17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_processingjob_node_status_state_machine"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectUploadSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upload_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("filename", models.CharField(max_length=255)),
                ("storage_key", models.TextField(unique=True)),
                ("content_type", models.CharField(blank=True, max_length=255)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("chunk_size_bytes", models.PositiveIntegerField(default=8388608)),
                ("chunk_count", models.PositiveIntegerField(default=1)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploading", "Uploading"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                (
                    "file_role",
                    models.CharField(
                        choices=[
                            ("sample", "Sample"),
                            ("qc", "QC"),
                            ("library", "Library"),
                            ("blank", "Blank"),
                            ("wash", "Wash"),
                            ("calibration", "Calibration"),
                        ],
                        default="sample",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "completed_raw_file",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_upload_session",
                        to="core.rawfile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_upload_sessions",
                        to="core.project",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="direct_upload_sessions",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at", "filename"),
            },
        ),
    ]
