# Generated by Django 5.2.15 on 2026-07-23 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_directuploadsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawFileDerivative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "derivative_type",
                    models.CharField(
                        choices=[
                            ("mzml", "mzML"),
                            ("mzmlb", "mzMLb"),
                            ("mgf", "MGF"),
                            ("spectrum_index", "Spectrum index"),
                            ("preview_json", "Preview JSON"),
                            ("vendor_metadata", "Vendor metadata"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                ("path", models.TextField()),
                ("format", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_file_derivatives",
                        to="core.processingjob",
                    ),
                ),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derivatives",
                        to="core.rawfile",
                    ),
                ),
            ],
            options={
                "ordering": ("raw_file", "derivative_type", "-updated_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raw_file", "derivative_type", "path"),
                        name="uniq_raw_file_derivative_path",
                    )
                ],
            },
        ),
    ]
