# Generated by Codex on 2026-07-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rawfilederivative"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingjob",
            name="stats",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ProcessingJobArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("log", "Log"),
                            ("protein_table", "Protein table"),
                            ("peptide_table", "Peptide table"),
                            ("diann_report", "DIA-NN report"),
                            ("fragpipe_output", "FragPipe output"),
                            ("enterprise_export", "Enterprise export"),
                            ("matrix", "Matrix"),
                            ("raw_output", "Raw output"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("path", models.TextField()),
                ("format", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("retained", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="core.processingjob",
                    ),
                ),
            ],
            options={
                "ordering": ("job", "artifact_type", "-updated_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "artifact_type", "path"),
                        name="uniq_processing_artifact_path",
                    )
                ],
            },
        ),
    ]
