# Generated by Codex on 2026-07-23

import json
from pathlib import Path

from django.db import migrations


def _file_size(path_value):
    try:
        path = Path(path_value)
        return path.stat().st_size if path.exists() and path.is_file() else None
    except (OSError, TypeError, ValueError):
        return None


def _artifact(apps, *, job, artifact_type, path, artifact_format):
    if not path:
        return
    ProcessingJobArtifact = apps.get_model("core", "ProcessingJobArtifact")
    ProcessingJobArtifact.objects.update_or_create(
        job=job,
        artifact_type=artifact_type,
        path=str(path),
        defaults={
            "format": artifact_format,
            "size_bytes": _file_size(path),
            "retained": True,
            "metadata": {"backfilled": True},
        },
    )


def _spectrum_counts(path_value):
    try:
        with Path(path_value).open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, TypeError, ValueError, json.JSONDecodeError):
        return {}
    spectra = payload.get("spectra") if isinstance(payload, dict) else []
    if not isinstance(spectra, list):
        spectra = []
    return {
        "indexed_spectra_count": len(spectra),
        "indexed_ms1_spectra_count": sum(1 for item in spectra if item.get("ms_level") == 1),
        "indexed_ms2_spectra_count": sum(1 for item in spectra if item.get("ms_level") == 2),
    }


def forwards(apps, schema_editor):
    ProcessingJob = apps.get_model("core", "ProcessingJob")
    RawFileDerivative = apps.get_model("core", "RawFileDerivative")

    for job in ProcessingJob.objects.all().iterator():
        metadata = job.metadata or {}
        result_import = metadata.get("result_import") or {}
        result_files = metadata.get("result_files") or {}
        stats = dict(job.stats or {})

        stats.setdefault("protein_quant_count", result_import.get("protein_quant_rows", 0))
        stats.setdefault("protein_identification_count", result_import.get("protein_ident_rows", 0))
        stats.setdefault("peptide_quant_count", result_import.get("peptide_quant_rows", 0))
        stats.setdefault("peptide_identification_count", result_import.get("peptide_ident_rows", 0))

        _artifact(
            apps,
            job=job,
            artifact_type="protein_table",
            path=result_files.get("protein_table_path"),
            artifact_format="table",
        )
        _artifact(
            apps,
            job=job,
            artifact_type="peptide_table",
            path=result_files.get("peptide_table_path"),
            artifact_format="table",
        )
        _artifact(apps, job=job, artifact_type="log", path=job.log_path, artifact_format="log")

        derivatives = RawFileDerivative.objects.filter(
            raw_file_id=job.raw_file_id,
            derivative_type__in=("spectrum_index", "preview_json"),
            status="ready",
        )
        for derivative in derivatives:
            for key, value in _spectrum_counts(derivative.path).items():
                stats.setdefault(key, value)

        if stats != (job.stats or {}):
            job.stats = stats
            job.save(update_fields=["stats"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_processingjob_stats_processingjobartifact"),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
