# Generated by Django 5.2.15 on 2026-07-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_backfill_processing_artifacts_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="qc_program",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("hye", "HYE"), ("prtc", "PRTC")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="worklistentry",
            name="qc_program",
            field=models.CharField(
                blank=True,
                choices=[("", "None"), ("hye", "HYE"), ("prtc", "PRTC")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="directuploadsession",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("hye", "HYE"),
                    ("prtc", "PRTC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("true_blank", "True blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="rawfile",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("hye", "HYE"),
                    ("prtc", "PRTC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("true_blank", "True blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="run",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("hye", "HYE"),
                    ("prtc", "PRTC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("true_blank", "True blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="worklistentry",
            name="file_role",
            field=models.CharField(
                choices=[
                    ("sample", "Sample"),
                    ("qc", "QC"),
                    ("hye", "HYE"),
                    ("prtc", "PRTC"),
                    ("library", "Library"),
                    ("blank", "Blank"),
                    ("true_blank", "True blank"),
                    ("wash", "Wash"),
                    ("calibration", "Calibration"),
                ],
                default="sample",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RawFileArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("archived", "Archived"),
                            ("restoring", "Restoring"),
                            ("restored", "Restored"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=32,
                    ),
                ),
                ("archive_path", models.TextField()),
                ("original_storage_path", models.TextField()),
                ("compression", models.CharField(default="zip", max_length=32)),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "raw_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archives",
                        to="core.rawfile",
                    ),
                ),
            ],
            options={
                "ordering": ("raw_file", "-updated_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raw_file", "archive_path"),
                        name="uniq_raw_file_archive_path",
                    )
                ],
            },
        ),
    ]
