# Generated by Codex on 2026-07-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_run_qc_program_worklistentry_qc_program_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawfilearchive",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("archiving", "Archiving"),
                    ("archived", "Archived"),
                    ("verifying", "Verifying"),
                    ("verified", "Verified"),
                    ("restoring", "Restoring"),
                    ("restored", "Restored"),
                    ("failed", "Failed"),
                ],
                default="planned",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="RawFileArchiveCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("copy_role", models.CharField(default="archive", max_length=32)),
                ("storage_root", models.TextField()),
                ("path", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("copying", "Copying"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="planned",
                        max_length=32,
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="core.rawfilearchive",
                    ),
                ),
            ],
            options={
                "ordering": ("archive", "copy_role", "path"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("archive", "path"),
                        name="uniq_raw_file_archive_copy_path",
                    )
                ],
            },
        ),
    ]
