# Generated by Django 5.2.15 on 2026-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rawfilearchivecopy_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectintakerequest",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="hazards_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="institution_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="invoice_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="matrix",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="organism",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="plate_format",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="projectintakerequest",
            name="shipping_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
