# Generated by Django 5.2.15 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_projectintakerequest_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="directuploadsession",
            name="intended_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="directuploadsession",
            name="match_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
