# Generated by Django 5.2.15 on 2026-08-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_directuploadsession_match_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentSetting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(default="site", max_length=32, unique=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "prtc_skyline_pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.processingpipeline",
                    ),
                ),
                (
                    "targeted_skyline_pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.processingpipeline",
                    ),
                ),
            ],
            options={
                "ordering": ("scope",),
            },
        ),
    ]
