# Generated by Django 5.2.15 on 2026-09-01 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_analysis_presets(apps, schema_editor):
    AnalysisPreset = apps.get_model("core", "AnalysisPreset")
    presets = [
        ("dia-library", "DIA discovery with library", "dia_library", "Quantify DIA runs against an existing spectral library."),
        ("dia-library-free", "DIA library-free discovery", "dia_library_free", "Run library-free DIA discovery with predicted spectral content."),
        ("dia-library-build", "DIA spectral-library build", "dia_library_build", "Build a project spectral library from the acquisition series."),
        ("dia-method-development", "DIA method development", "dia_method_development", "Compare acquisition or LC method versions across runs."),
        ("dia-qc", "DIA system suitability", "dia_qc", "Evaluate QC and system-suitability injections."),
    ]
    for code, name, analysis_type, description in presets:
        AnalysisPreset.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "analysis_type": analysis_type,
                "description": description,
                "required_metadata": ["sample_name", "expected_filename"],
                "active": True,
            },
        )


def remove_analysis_presets(apps, schema_editor):
    apps.get_model("core", "AnalysisPreset").objects.filter(
        code__in=("dia-library", "dia-library-free", "dia-library-build", "dia-method-development", "dia-qc")
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_experiment_completed_at_experiment_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("dia_library", "DIA discovery with library"),
                            ("dia_library_free", "DIA library-free discovery"),
                            ("dia_library_build", "DIA spectral-library build"),
                            ("dia_method_development", "DIA method development"),
                            ("dia_qc", "DIA system suitability"),
                        ],
                        max_length=64,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("defaults", models.JSONField(blank=True, default=dict)),
                ("required_metadata", models.JSONField(blank=True, default=list)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name", "code"),
            },
        ),
        migrations.AlterField(
            model_name="pipelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("file_discovered", "File discovered"),
                    ("file_uploaded", "File uploaded"),
                    ("file_stored", "File stored"),
                    ("match_exception_created", "Match exception created"),
                    ("file_matched", "File matched"),
                    ("raw_file_imported", "Raw file imported"),
                    ("processing_queued", "Processing queued"),
                    ("processing_started", "Processing started"),
                    ("processing_completed", "Processing completed"),
                    ("result_files_uploaded", "Result files uploaded"),
                    ("results_parsed", "Results parsed"),
                    ("experiment_completed", "Experiment completed"),
                    ("project_completed", "Project completed"),
                    ("settings_updated", "Settings updated"),
                    ("migration_imported", "Migration imported"),
                ],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="FileMatchException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField()),
                ("candidate_metadata", models.JSONField(blank=True, default=dict)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_match_exceptions",
                        to="core.experiment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_match_exceptions",
                        to="core.project",
                    ),
                ),
                (
                    "raw_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_exception",
                        to="core.rawfile",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_match_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_match_exceptions",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "ordering": ("status", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SampleManifest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("processing", "Processing"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "analysis_preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifests",
                        to="core.analysispreset",
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifests",
                        to="core.experiment",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sample_manifests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SampleManifestRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("sample_name", models.CharField(max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=128)),
                ("expected_filename", models.CharField(max_length=255)),
                ("condition", models.CharField(blank=True, max_length=128)),
                ("replicate", models.CharField(blank=True, max_length=64)),
                ("batch", models.CharField(blank=True, max_length=128)),
                ("method_version", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "manifest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.samplemanifest",
                    ),
                ),
                (
                    "matched_run",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manifest_row",
                        to="core.run",
                    ),
                ),
            ],
            options={
                "ordering": ("manifest", "row_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("manifest", "row_number"),
                        name="uniq_manifest_row_number",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_analysis_presets, remove_analysis_presets),
    ]
