# Generated by Django 5.2.15 on 2026-09-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_processingjob_leases"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingnode",
            name="release_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="processingnode",
            name="release_status",
            field=models.CharField(default="unknown", max_length=32),
        ),
        migrations.AddField(
            model_name="processingnode",
            name="reported_release",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="DeploymentRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=128)),
                (
                    "channel",
                    models.CharField(
                        choices=[("staging", "Staging"), ("production", "Production")],
                        default="staging",
                        max_length=32,
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("digest", models.CharField(blank=True, max_length=128)),
                ("release_notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "channel"),
                        name="uniq_release_version_channel",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="processingnode",
            name="desired_release",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="desired_nodes",
                to="core.deploymentrelease",
            ),
        ),
    ]
