# Generated by Django 5.2.15 on 2026-09-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_processingnode_release_error_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
