# Generated by Django 5.2.15 on 2026-09-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_processingnodeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklistentry",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
