# Generated by Django 5.2.15 on 2026-09-16 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_worklistentry_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="worklistentry",
            name="uniq_worklist_expected_filename",
        ),
        migrations.AddField(
            model_name="acquisitionworklist",
            name="frozen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="acquisitionworklist",
            name="frozen_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="frozen_worklists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acquisitionworklist",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="worklistentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("worklist", "expected_filename"),
                name="uniq_active_worklist_expected_filename",
            ),
        ),
    ]
