# Generated by Django 5.2.15 on 2026-09-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_worklistentry_uniq_worklist_expected_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peptideidentification",
            name="q_value_context",
            field=models.CharField(default="run", max_length=64),
        ),
        migrations.AddField(
            model_name="peptideidentification",
            name="q_value_level",
            field=models.CharField(default="precursor", max_length=64),
        ),
        migrations.AddField(
            model_name="proteinidentification",
            name="q_value_context",
            field=models.CharField(default="run", max_length=64),
        ),
        migrations.AddField(
            model_name="proteinidentification",
            name="q_value_level",
            field=models.CharField(default="protein_group", max_length=64),
        ),
    ]
